# Generated by Django 4.2 on 2024-07-30 03:49

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AksesStaf',
            fields=[
                ('akses_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dapat_akses', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('gudang_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_gudang', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('lokasi', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('pusat', 'Gudang Pusat'), ('cabang', 'Gudang Cabang')], max_length=255)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('gudang_pusat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gudang')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('satuan', models.CharField(choices=[('pcs', 'Pieces'), ('paket', 'Paket')], max_length=20)),
                ('level_stok', models.PositiveIntegerField(default=0)),
                ('level_minimum', models.PositiveIntegerField(default=0)),
                ('stok_aktual', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('lokasi_rak', models.CharField(blank=True, max_length=100, null=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gudang')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('kategori_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LokasiToko',
            fields=[
                ('lokasi_toko_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gudang')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineShop',
            fields=[
                ('online_shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_online_shop', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_resi', models.CharField(max_length=255)),
                ('nama_customer', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('kota_kecamatan', models.CharField(max_length=500)),
                ('metode_pembayaran', models.CharField(choices=[('cod', 'Cash On Delivery'), ('transfer', 'Transfer Bank')], max_length=255)),
                ('total_qty', models.PositiveIntegerField()),
                ('total_pembayaran', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ongkos_kirim', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tanggal_order', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proses', 'Proses'), ('siap', 'Siap Kirim'), ('dikirim', 'Sudah Dikirim'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan'), ('retur', 'retur')], default='pending', editable=False, max_length=50)),
                ('resi', models.FileField(upload_to=core.utils.order_resi_pdf_path)),
                ('lokasi_kirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gudang')),
            ],
        ),
        migrations.CreateModel(
            name='TokoOnlineShop',
            fields=[
                ('toko_online_shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_toko', models.CharField(max_length=255)),
                ('nama_toko', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('penanggung_jawab', models.CharField(max_length=255)),
                ('online_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.onlineshop')),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('stok_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('lokasi_rak', models.CharField(blank=True, max_length=100, null=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gudang')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto_profile', models.ImageField(upload_to=core.utils.staf_image_path)),
                ('nama_staff', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('tanggal_masuk', models.DateField()),
                ('gudang', models.ManyToManyField(through='core.AksesStaf', to='core.gudang')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('produk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=500)),
                ('deskripsi', models.TextField()),
                ('harga_hpp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('gambar', models.ImageField(upload_to=core.utils.produk_image_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='produk',
            field=models.ManyToManyField(through='core.OrderItem', to='core.inventory'),
        ),
        migrations.AddField(
            model_name='order',
            name='toko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lokasitoko'),
        ),
        migrations.AddField(
            model_name='lokasitoko',
            name='toko_online_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tokoonlineshop'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk'),
        ),
        migrations.CreateModel(
            name='AktivitasGudang',
            fields=[
                ('aktivitas_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis_aktivitas', models.CharField(choices=[('masuk', 'Barang Masuk'), ('keluar', 'Barang Keluar'), ('sesuaikan', 'Penyesuaian Stok')], max_length=20)),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal_aktivitas', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('nama_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='aksesstaf',
            name='gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gudang'),
        ),
        migrations.AddField(
            model_name='aksesstaf',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
        ),
    ]
