# Generated by Django 4.2 on 2024-07-26 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('kategori_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('produk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=500)),
                ('deskripsi', models.TextField()),
                ('harga_hpp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gambar', models.ImageField(upload_to='produk_gambar/')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
            ],
        ),
    ]
