# Generated by Django 4.2 on 2024-07-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
