# Generated by Django 4.2 on 2024-07-29 16:21

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='jumlah',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty_produk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tanggal_selesai',
        ),
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='resi',
            field=models.FileField(upload_to=core.utils.order_resi_pdf_path),
        ),
    ]
