# Generated by Django 4.2 on 2024-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_jumlah_orderitem_qty_remove_order_qty_produk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tanggal_selesai',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
