# Generated by Django 4.2 on 2024-07-30 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_total_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('pelanggan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('pesanan', models.ManyToManyField(to='core.order')),
            ],
        ),
    ]
