# Generated by Django 4.2 on 2024-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_tanggal_selesai_alter_order_total_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
