# Generated by Django 4.2 on 2024-07-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pelanggan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
