# Generated by Django 4.2 on 2024-07-27 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aksesstaf_gudang_staff_aksesstaf_gudang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('satuan', models.CharField(choices=[('pcs', 'Pieces'), ('paket', 'Paket')], max_length=20)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level_stok', models.PositiveIntegerField(default=0)),
                ('level_minimum', models.PositiveIntegerField(default=0)),
                ('stok_aktual', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('lokasi_rak', models.CharField(blank=True, max_length=100, null=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gudang')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('stok_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('lokasi_rak', models.CharField(blank=True, max_length=100, null=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gudang')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='AktivitasGudang',
            fields=[
                ('aktivitas_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis_aktivitas', models.CharField(choices=[('masuk', 'Barang Masuk'), ('keluar', 'Barang Keluar'), ('adjustment', 'Penyesuaian Stok')], max_length=20)),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal_aktivitas', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('nama_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stok')),
            ],
        ),
    ]
