# Generated by Django 4.2 on 2024-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inventory_stok_aktivitasgudang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='harga_beli',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='harga_jual',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='batch_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
