# Generated by Django 4.2 on 2024-07-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_inventory_harga_beli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stok',
            name='batch_number',
        ),
    ]
