# Generated by Django 4.2 on 2024-07-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_stok_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitasgudang',
            name='stok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
    ]
