# Generated by Django 4.2 on 2024-07-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aktivitasgudang_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitasgudang',
            name='jenis_aktivitas',
            field=models.CharField(choices=[('masuk', 'Barang Masuk'), ('keluar', 'Barang Keluar'), ('sesuaikan', 'Penyesuaian Stok')], max_length=20),
        ),
    ]
